### ISSUE TITLE
callbag-share?

### ISSUE THREAD

**Issue by staltz** [sartaj/pipe-me#1]
Hi! I noticed you had this line about multicast: https://github.com/sartaj/pipe-me/blob/4dceed4e867f07fc7e3c180617da3956d714f386/index.js#L12

Are you aware of callbag-share? It's in basics. It would create multicasting. :)

**Comment by sartaj** [comment]
@staltz Like `xstream`, my goal is to have the callbags in this system be multicast by default.

I used `callbag-share` to add multicasting to all creators, and now also exposed `share` as part of the library here. Here is the commit: https://github.com/sartaj/pipe-me/commit/07381a2fc4f69ea9ae67e73c28669caf092dd6f8

I would love your opinion if you feel this is improperly implemented. Thanks for all your help.
